name: Release on Version Change

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine if version has changed
        id: version_changed
        run: |
          if [[ $(git diff --name-only HEAD^ HEAD package.json | grep version) ]]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create release if version has changed
        if: steps.version_changed.outputs.version_changed == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: 'v${{ env.npm_package_version }}'
          release_name: 'Dego-package v${{ env.npm_package_version }}'
          draft: false
          prerelease: false
