name: Release on Version Change

on:
  push:
    branches: [main]

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Makepad-fr/auto-release-on-version-bump-action@0.0.2
        with:
          token: ${{ secrets.PAT }}
          name: 'Dego-package v$newVersion'
          body: ''
          draft: 'false'
          pre-release: 'false'
          generate-release-note: 'true'
          tag-name: 'v$newVersion'
          fail-on-unchanged-version: 'false'
